name: Build and Attach Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Extract release tag and update pom.xml
      - name: Update pom.xml version
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          echo "Updating pom.xml version to $RELEASE_TAG"
          sed -i '0,/<version>.*<\/version>/s/<version>.*<\/version>/<version>'"${RELEASE_TAG}"'<\/version>/' pom.xml

      # Step 3: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug POM
        run: cat pom.xml

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean package

      - name: List files in directory
        run: ls -R

      # Step 5: Attach the built JAR to the release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/HeadHunters-${{ github.event.release.tag_name }}.jar
          asset_name: HeadHunters-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
